FROM ubuntu:focal 

WORKDIR /api

COPY ./requirements.txt .

RUN apt update -y && apt upgrade -y

RUN apt install build-essential python3 -y && apt install python-dev -y

RUN apt install python3-pip -y

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]

